### ISSUE TITLE
add terms to glossary

### ISSUE THREAD

**Issue by davelandry** [data-africa/data-africa-site#113]
* [x] Headcount Ratio
* [x] Poverty Gap Ratio
* [x] Poverty Severity Ratio
* [x] Rainfall Variability
* [x] explanation of "age of reference"

**Comment by davelandry** [comment]
@jspeis what about age of reference?

**Comment by jspeis** [comment]
we can simply alter the term "age of reference" to make it more straighforward e.g.

> Wasted: Below minus two standard deviations from median weight for height of the given population.
