### ISSUE TITLE
find a monospace font for numbers

### ISSUE THREAD

**Issue by davelandry** [data-africa/data-africa-site#116]
For example, the numbers listed in tooltips and on the map page would be easier to read if we use a monospace font:

<img width="293" alt="screen shot 2017-05-17 at 6 55 09 pm" src="https://cloud.githubusercontent.com/assets/1847581/26179581/7c43e9f0-3b32-11e7-91b6-9a072d96944d.png">

@housegeoff if you can find a monospace Google Font that you like, please post a mockup here and I can hook up the overrides in code

**Comment by davelandry** [comment]
Tried Source Code Pro. "Meh"
<img width="282" alt="screen shot 2017-06-22 at 3 03 51 pm" src="https://user-images.githubusercontent.com/1847581/27451123-0e840d78-575c-11e7-95c1-d5ff55f6b944.png">

**Comment by housegeoff** [comment]
@davelandry haha it's a monospace font! What more do you want!? I'd either try the medium weight or for a different font Roboto Mono: https://fonts.google.com/specimen/Roboto+Mono

**Comment by davelandry** [comment]
Ohhh Roboto Mono is nice, what do you think?

<img width="282" alt="screen shot 2017-06-22 at 6 19 15 pm" src="https://user-images.githubusercontent.com/1847581/27458490-5aa14610-5777-11e7-9d17-2a2417a37e7b.png">
