### ISSUE TITLE
poverty levels seem really large

### ISSUE THREAD

**Issue by davelandry** [data-africa/data-africa-site#13]

**Comment by jspeis** [comment]
![screen shot 2017-02-07 at 9 51 40 am](https://cloud.githubusercontent.com/assets/87581/22696523/43d917c0-ed1c-11e6-90a6-23a596ab03c7.png)

The values in the raw data are large. Going to double check with/Carlo that the originals are correct

**Comment by jspeis** [comment]
Confirmed with Carlo, that the numbers actually are that large
