### ISSUE TITLE
for health vizs, align alike severities

### ISSUE THREAD

**Issue by jspeis** [data-africa/data-africa-site#27]
![screen shot 2017-02-27 at 6 13 46 pm](https://cloud.githubusercontent.com/assets/87581/23384350/83f4640c-fd18-11e6-89c4-a9c15a9c8406.png)

e.g. if the male and female severe wasted boxes are adjacent it is easier to compare which gender has a greater proportion of impacted children

**Comment by davelandry** [comment]
@jspeis been doing some testing in d3plus for this, totally doable
