### ISSUE TITLE
add pullout stats for all sections

### ISSUE THREAD

**Issue by jspeis** [data-africa/data-africa-site#49]
![screen shot 2017-03-15 at 9 14 03 am](https://cloud.githubusercontent.com/assets/87581/23950021/fc57489e-095f-11e7-99e6-a386ddd8b61b.png)

**Comment by housegeoff** [comment]
@davelandry is this something I can be working on or should I be waiting for updated pullout content?

**Comment by davelandry** [comment]
we can get this hooked up for you

**Comment by davelandry** [comment]
@housegeoff can I get your eyeballs on this?

<img width="1248" alt="screen shot 2017-06-23 at 12 08 48 pm" src="https://user-images.githubusercontent.com/1847581/27490568-c65f8ade-580c-11e7-9f90-d8df93d59a97.png">

<img width="1255" alt="screen shot 2017-06-23 at 12 45 07 pm" src="https://user-images.githubusercontent.com/1847581/27491821-d87fb2ca-5811-11e7-84fd-cd7b72f27435.png">
