### ISSUE TITLE
fix stacked bar ordering

### ISSUE THREAD

**Issue by davelandry** [data-africa/data-africa-site#52]
the darker more severe colors should always be on bottom

**Comment by davelandry** [comment]
@jspeis @housegeoff can either of you guys find a page where this is still happening? did I fix this? am I dreaming?

**Comment by jspeis** [comment]
![screen shot 2017-03-28 at 11 04 58 am](https://cloud.githubusercontent.com/assets/87581/24412566/ce6acea0-13a6-11e7-91f8-0be7409c0ff0.png)
the only place I see it now is when looking at "Health Conditions Among Children" the ordering isn't preserved across conditions

**Comment by housegeoff** [comment]
@davelandry @jspeis Looks like the stacking is fixed for Health Conditions Among Children, but persists for the following two charts: By Gender and By Residence. I actually get different results depending on the country and or region :/

Countries
http://localhost:3300/profile/040AF00155
http://localhost:3300/profile/040AF00182

Regions 
http://localhost:3300/profile/050AF0015501927
http://localhost:3300/profile/050AF0018202216

**Comment by davelandry** [comment]
finally fixed (with an `rm -r node_modules && npm i` of course)

d3-shape's [stack.order](https://github.com/d3/d3-shape#stack_order) property is a tricky one, but I've now baked some logic into d3plus so that you can just tell it an array to order by
