### ISSUE TITLE
re-export dropdown arrow

### ISSUE THREAD

**Issue by davelandry** [data-africa/data-africa-site#57]
@housegeoff the dropdown arrow is appearing as a grey box for me and @jspeis. it looks like the svg didn't export/save correctly?

**Comment by davelandry** [comment]
@housegeoff your merge doesn't fix this issue. When I view the SVGs as text, I can see that Sketch is exporting the icons as text elements. you can even see where the grey square is coming from:
```html
<tspan x="4.16015625" y="19"></tspan>
```

Are you using a font for these icons? If so, you need to convert the text to outlines before exporting.

**Comment by housegeoff** [comment]
@davelandry Yep that's the conclusion I came to aswell. The updated svg should have been committed though. Is it working for you now?
