### ISSUE TITLE
stack climate visualizations on top of each other and make taller

### ISSUE THREAD

**Issue by davelandry** [data-africa/data-africa-site#69]
for two reasons:
* the bar chart on a province page (like Borno) is very dense)
* the whole Climate section is very short, and this would help make it feel larger

**Comment by housegeoff** [comment]
@davelandry what if we shift this one viz back to the row layout with text on top. I think the visuals work best side by side. This way they could take up the full width and we could still make them taller. I can tackle this one if that's okay.
