### ISSUE TITLE
decide on a consistent color scale for all maps

### ISSUE THREAD

**Issue by davelandry** [data-africa/data-africa-site#70]
The green scale on the Map page is very very light. It's better for the color scale to use a darker color, so that the bins have more contrast. The blue used for rainfall is great, but would this make sense to use on the full-screen Map page?

@housegeoff we leave it up to you to either say "yeah let's use that blue color everywhere", or find a richer/darker color to use everywhere.

**Comment by housegeoff** [comment]
@davelandry I think we can use blue across the board. 4 out of 15 map categories are rainfall related anyway. The other option would be to do category specific colors, blue for rainfall, green for crops stats, orangey or purple for people data... I like that idea a lot but I don't know how difficult it is to implement.

**Comment by davelandry** [comment]
Not too difficult to implement different scales, but I'm of the opinion that it would be confusing! Let's switch everything to the rainfall blue or the time being.
