### ISSUE TITLE
year control toggle on health by gender not updating bolded font for selected year

### ISSUE THREAD

**Issue by jspeis** [data-africa/data-africa-site#83]

**Comment by davelandry** [comment]
I'm able to confirm that this bug only appears in the final webpack build (`npm run build && npm start`), not in the normal dev environment.

**Comment by davelandry** [comment]
I believe this is fixed, please re-open this issue if someone is able to replicate it.

**Comment by davelandry** [comment]
Also, requires a `rm -r node_modules/ && npm i` to fix.
